name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Build
      run: go mod download github.com/webngt/timeutils 

    - name: Test
      run: go test github.com/webngt/timeutils
